BRIEFPAPIER_BREEDTE_INCHES = 8.5
BRIEFPAPIER_HOOGTE_INCHES = 11

INCH_ALS_MILLIMETER = 25.4

# round omdat er door de float anders .99999999 bijstaat
BRIEFPAPIER_BREEDTE_MILLIMETER = round(BRIEFPAPIER_BREEDTE_INCHES * INCH_ALS_MILLIMETER, 1)
BRIEFPAPIER_HOOGTE_MILLIMETER = round(BRIEFPAPIER_HOOGTE_INCHES * INCH_ALS_MILLIMETER, 1)


print("USA letter dimension in millimeters: " + str(BRIEFPAPIER_BREEDTE_MILLIMETER) + " x " + str(BRIEFPAPIER_HOOGTE_MILLIMETER))